from atm_simulator.domain import ATMState, STATE_PRECEDENCE


def test_atm_state_precedence_order():
    assert STATE_PRECEDENCE[ATMState.DOWN_FAILURE] > STATE_PRECEDENCE[ATMState.DOWN_MAINTENANCE]
    assert STATE_PRECEDENCE[ATMState.DOWN_MAINTENANCE] > STATE_PRECEDENCE[ATMState.CASHOUT]
    assert STATE_PRECEDENCE[ATMState.CASHOUT] > STATE_PRECEDENCE[ATMState.BUSY]
    assert STATE_PRECEDENCE[ATMState.BUSY] > STATE_PRECEDENCE[ATMState.IDLE]
